In [20]:
print("Hello World")

Hello World


In [22]:
import torch

In [30]:
# 使用pytorch实现identity matrix 与 向量相乘的例子
# 创建一个向量
vector = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

# 创建一个与向量维度相同的单位矩阵
identity_matrix = torch.eye(vector.size(0))

# 执行矩阵乘法
result = torch.matmul(identity_matrix, vector)

print("原始向量:", vector)
print("单位矩阵:")
print(identity_matrix)
print("结果:", result)

原始向量: tensor([1., 2., 3., 4., 5.])
单位矩阵:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
结果: tensor([1., 2., 3., 4., 5.])


In [34]:
# 矩阵的逆的定义为 A^-1 * A = I
# 使用pytorch求解一个矩阵的逆
matrix = torch.tensor([[1, 1], [2, 0]], dtype=torch.float32)
inverse_matrix = torch.inverse(matrix)
print("原始矩阵:")
print(matrix)
print("逆矩阵:")
print(inverse_matrix)

原始矩阵:
tensor([[1., 1.],
        [2., 0.]])
逆矩阵:
tensor([[ 0.0000,  0.5000],
        [ 1.0000, -0.5000]])


In [35]:
# 使用矩阵的逆求解线性方程
# A * x = b
# A^-1 * A * x = A^-1 * b
# x = A^-1 * b
matrix = torch.tensor([[1, 1], [2, 0]], dtype=torch.float32)
inverse_matrix = torch.inverse(matrix)
vector = torch.tensor([2, 1], dtype=torch.float32)
solution = torch.matmul(inverse_matrix, vector)
print("原始矩阵:")
print(matrix)
print("逆矩阵:")
print(inverse_matrix)
print("原始向量:", vector)
print("解:", solution)

原始矩阵:
tensor([[1., 1.],
        [2., 0.]])
逆矩阵:
tensor([[ 0.0000,  0.5000],
        [ 1.0000, -0.5000]])
原始向量: tensor([2., 1.])
解: tensor([0.5000, 1.5000])
