In [1]:
# A random variable is a variable that can take on different values randomly

In [5]:
# PMF 概率质量函数 离散随机变量每个值的取值概率
# PDF 概率密度函数 连续随机变量每个值的取值概率
# X ～ p(X) 离散随机标量X服从分布p(X)
# 离散随机变量，p(x)表示，p(X=x)

联合概率、边缘概率、条件概率和贝叶斯公式

In [3]:
# 离散随机变量

import numpy as np

# 定义联合概率分布
P_xy = np.array([[0.1, 0.2, 0.1],  # P(X=0, Y=0), P(X=0, Y=1), P(X=0, Y=2)
                 [0.3, 0.0, 0.1],  # P(X=1, Y=0), P(X=1, Y=1), P(X=1, Y=2)
                 [0.1, 0.1, 0.0]]) # P(X=2, Y=0), P(X=2, Y=1), P(X=2, Y=2)

# 计算边缘概率
P_x = P_xy.sum(axis=1)  # P(X)
P_y = P_xy.sum(axis=0)  # P(Y)

# 计算条件概率 P(Y|X)
P_Y_given_X = P_xy / P_x[:, np.newaxis]

# 打印结果
print("联合概率 P(X, Y):")
print(P_xy)
print("边缘概率 P(X):", P_x)
print("边缘概率 P(Y):", P_y)
print("条件概率 P(Y|X):")
print(P_Y_given_X)

联合概率 P(X, Y):
[[0.1 0.2 0.1]
 [0.3 0.  0.1]
 [0.1 0.1 0. ]]
边缘概率 P(X): [0.4 0.4 0.2]
边缘概率 P(Y): [0.5 0.3 0.2]
条件概率 P(Y|X):
[[0.25 0.5  0.25]
 [0.75 0.   0.25]
 [0.5  0.5  0.  ]]


In [6]:
# 贝叶斯公式

# 定义先验概率 P(A) 和 P(B|A)
P_A = 0.3  # 事件 A 发生的先验概率
P_B_given_A = 0.8  # 事件 B 在 A 发生的情况下的概率

# 计算 P(B) = P(B|A) * P(A) + P(B|¬A) * P(¬A)
P_not_A = 1 - P_A  # 事件 A 不发生的概率
P_B_given_not_A = 0.5  # 假定事件 B 在 A 不发生的情况下的概率

# 计算 P(B)
P_B = P_B_given_A * P_A + P_B_given_not_A * P_not_A

# 使用贝叶斯公式计算 P(A|B)
P_A_given_B = (P_B_given_A * P_A) / P_B

# 打印结果
print("P(A|B):", P_A_given_B)

P(A|B): 0.631578947368421


两个随机变量相互独立

In [7]:
# 相互独立：P(X,Y)=P(X)⋅P(Y)
# 条件独立：P(X,Y∣Z)=P(X∣Z)⋅P(Y∣Z)

import numpy as np

# 定义概率分布
P_X = 0.5  # P(X=1)
P_Y = 0.3  # P(Y=1)

# 计算 P(X, Y) 假设 X 和 Y 是独立的
P_XY_independent = P_X * P_Y

# 假设观察到的联合概率
P_XY_observed = 0.15

# 检查独立性
is_independent = np.isclose(P_XY_independent, P_XY_observed)
print("X 和 Y 相互独立:", is_independent)

X 和 Y 相互独立: True
