In [1]:
# 对角矩阵：只有对角线为非负值的矩阵
# 对角矩阵的逆 = 对角线上的值的倒数的转置
# 对称矩阵：转置等于自己 a_i_j = a_j_i
# 单位向量：向量的L2范数为1
# 向量x与y正交：x的转置与y相乘=0
# orthonormal（正交规范）：单位向量彼此正交
# orthonormal matrix（正交规范矩阵）：行向量或列向量orthonormal的矩阵，矩阵的转置乘以自己=单位阵 -> 矩阵的转置等于矩阵的逆

In [6]:
import torch

# 对角矩阵
diagonal_matrix = torch.diag(torch.tensor([1, 2, 3]))
print("对角矩阵：")
print(diagonal_matrix)

# 对角矩阵的逆
inverse_diagonal_matrix = torch.diag(1 / torch.tensor([1, 2, 3]))
print("\n对角矩阵的逆：")
print(inverse_diagonal_matrix)

# 对称矩阵
symmetric_matrix = torch.tensor([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("\n对称矩阵：")
print(symmetric_matrix)

# 单位向量
unit_vector = torch.tensor([1, 0, 0]) / torch.norm(torch.tensor([1, 0, 0], dtype=torch.float))
print("\n单位向量：")
print(unit_vector)

# 正交向量
orthogonal_vector1 = torch.tensor([1, 0, 0])
orthogonal_vector2 = torch.tensor([0, 1, 0])
dot_product = torch.dot(orthogonal_vector1, orthogonal_vector2)
print("\n正交向量的点积：")
print(dot_product)

# 正交归一化矩阵
orthonormal_matrix = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("\n正交归一化矩阵：")
print(orthonormal_matrix)

# 验证正交归一化
orthonormal_check = torch.transpose(orthonormal_matrix, 0, 1) @ orthonormal_matrix
print("\n正交归一化矩阵的验证（转置乘以自身）：")
print(orthonormal_check)

对角矩阵：
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

对角矩阵的逆：
tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.3333]])

对称矩阵：
tensor([[1, 2, 3],
        [2, 4, 5],
        [3, 5, 6]])

单位向量：
tensor([1., 0., 0.])

正交向量的点积：
tensor(0)

正交归一化矩阵：
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

正交归一化矩阵的验证（转置乘以自身）：
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
