In [1]:
# 特征值分解
# 参考：https://www.bilibili.com/video/BV1TH4y1L7PV/ 漫士沉思录

In [2]:
# 特征值与特征向量究竟是什么含义？

# 把点x看成原坐标系的一个向量， 当矩阵A作用于x时，得到原坐标系的新的向量x'
# 当在原坐标系中，x与x'在同一条直线上，则称这条直线上的向量为特征向量
# 这条直线上所有向量都缩放一样的倍数，称之为特征值
# 找到A矩阵所有的特征值与特征向量，比如说A为2×2的矩阵，则最多有两个特征值
# 这时候如果不知道A矩阵本身，只知道特征值和特征向量所在的直线，那么一个任一点x，能够得到变换后的新的点x'的坐标吗？
# 答案是可以的，只需要把x，在特征向量所在的直线分解，然后分别缩放特征值倍，把缩放后的向量再合成，就可以得到x'的坐标了
# 所以：特征值和特征向量反映了A矩阵的空间变换性质

In [1]:
# 为什么要把矩阵A分解成：A=PΛP^−1
# We concatenate all eigenvectors to form a matrix P = (v1, . . . , vN )，P的列向量是相互独立的，因为还有求解它的逆
# We form all eigenvalues into a diagonal matrix Λ = diag(λ1, . . . , λN )^T
# (remark: by convention, we typically sort the eigenvalues in descending order)

# 1、V^−1相当于把原坐标系的点，表示为特征向量构成的坐标系
# 2、在特征向量为基的坐标系中，对其进行缩放
# 3、V相当于再还原到原来的坐标系，得到最终变换后的点在原坐标系的位置

好处：
比如说A^2，可以写成：
$$A^{2} = P\Lambda P^{-1}  P\Lambda P^{-1}  =P\Lambda^{2}P^{-1}$$
进而得到：
$$A^{n} = =P\Lambda^{n}P^{-1}$$
让矩阵连续相乘计算变得简单

In [3]:
# 用pytorch实现矩阵的特征值分解
import torch

# 创建一个方阵 A
A = torch.tensor([[4.0, 2.0],
                  [1.0, 3.0]])

# 进行特征值分解
eigenvalues, eigenvectors = torch.linalg.eig(A)

# 构造对角矩阵 Λ
Lambda = torch.diag(eigenvalues)

# 计算 P 的逆
P_inverse = torch.linalg.inv(eigenvectors)

# 验证 A = PΛP^−1
A_reconstructed = eigenvectors @ Lambda @ P_inverse

# 输出结果
print("特征值：")
print(eigenvalues)

print("特征向量：")
print(eigenvectors)

print("对角特征值矩阵 Λ：")
print(Lambda)

print("重构的 A：")
print(A_reconstructed)

特征值：
tensor([5.0000+0.j, 2.0000+0.j])
特征向量：
tensor([[ 0.8944+0.j, -0.7071+0.j],
        [ 0.4472+0.j,  0.7071+0.j]])
对角特征值矩阵 Λ：
tensor([[5.0000+0.j, 0.0000+0.j],
        [0.0000+0.j, 2.0000+0.j]])
重构的 A：
tensor([[4.0000+0.j, 2.0000+0.j],
        [1.0000+0.j, 3.0000+0.j]])
